-- MySQL Script generated by MySQL Workbench
-- mar 12 dic 2023 11:51:44
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ss2
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ss2` ;

-- -----------------------------------------------------
-- Schema ss2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ss2` ;
USE `ss2` ;

-- -----------------------------------------------------
-- Table `ss2`.`Country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ss2`.`Country` ;

CREATE TABLE IF NOT EXISTS `ss2`.`Country` (
  `code_country` VARCHAR(10) NOT NULL,
  `name_country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`code_country`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ss2`.`Departament`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ss2`.`Departament` ;

CREATE TABLE IF NOT EXISTS `ss2`.`Departament` (
  `code_department` VARCHAR(10) NOT NULL,
  `name_department` VARCHAR(45) NOT NULL,
  `code_country` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`code_department`),
  INDEX `fk_Departament_Country1_idx` (`code_country` ASC) VISIBLE,
  CONSTRAINT `fk_Departament_Country1`
    FOREIGN KEY (`code_country`)
    REFERENCES `ss2`.`Country` (`code_country`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ss2`.`Municipality`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ss2`.`Municipality` ;

CREATE TABLE IF NOT EXISTS `ss2`.`Municipality` (
  `code_municipality` VARCHAR(10) NOT NULL,
  `population` INT NOT NULL DEFAULT 0,
  `municipality` VARCHAR(45) NOT NULL,
  `code_department` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`code_municipality`),
  INDEX `fk_Municipality_Departament1_idx` (`code_department` ASC) VISIBLE,
  CONSTRAINT `fk_Municipality_Departament1`
    FOREIGN KEY (`code_department`)
    REFERENCES `ss2`.`Departament` (`code_department`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ss2`.`MunicipalityDeathsReported`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ss2`.`MunicipalityDeathsReported` ;

CREATE TABLE IF NOT EXISTS `ss2`.`MunicipalityDeathsReported` (
  `code_municipality` VARCHAR(10) NOT NULL,
  `date_reported` DATE NOT NULL,
  `new_deaths` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`code_municipality`, `date_reported`),
  INDEX `fk_MunicipalityDeathsReported_Municipality1_idx` (`code_municipality` ASC) VISIBLE,
  CONSTRAINT `fk_MunicipalityDeathsReported_Municipality1`
    FOREIGN KEY (`code_municipality`)
    REFERENCES `ss2`.`Municipality` (`code_municipality`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ss2`.`Cases`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ss2`.`Cases` ;

CREATE TABLE IF NOT EXISTS `ss2`.`Cases` (
  `code_country` VARCHAR(10) NOT NULL,
  `date_reported` DATE NOT NULL,
  `new_cases` INT NOT NULL DEFAULT 0,
  `cumulative_cases` INT NOT NULL DEFAULT 0,
  `new_deaths` INT NOT NULL DEFAULT 0,
  `cumulative_deaths` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`code_country`, `date_reported`),
  INDEX `fk_Case_Country1_idx` (`code_country` ASC) VISIBLE,
  CONSTRAINT `fk_Case_Country1`
    FOREIGN KEY (`code_country`)
    REFERENCES `ss2`.`Country` (`code_country`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ss2`.`Log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ss2`.`Log` ;

CREATE TABLE IF NOT EXISTS `ss2`.`Log` (
  `id_log` INT NOT NULL AUTO_INCREMENT,
  `message` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`id_log`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
